### ISSUE TITLE
read fails when passing BytesIO stream

### ISSUE THREAD

**Issue by Andyjo07** [dranjan/python-plyfile#19]
I've found that when reading ply files from a zipfile, and passing the binary stream into PlyData.read(), it crashes trying to create a numpy memmap.
```
from zipfile import ZipFile
from io import BytesIO
sourceFile = "somefile.zip"
targetFile = "p0.ply"
with ZipFile(sourceFile, 'r') as zz:
    nl = zz.namelist()
    if targetFile not in nl: return False
    plyBinData = BytesIO(zz.read(targetFile))

p = PlyData.read(plyBinData) # This throws the exception because BytesIO doesn't appreciate fileno()
```
If you import BytesIO add a check for a BytesIO stream instance in _read of PlyElement and add the following code it seems to work.
```
if isinstance(stream,BytesIO):
    stream.seek(0)
    self._data = _np.frombuffer(stream.read(),dtype=dtype,offset=offset,count=self.count)
else:
    self._data = _np.memmap(stream, dtype, 'c', offset, self.count)
```

**Comment by dranjan** [comment]
Thanks for the bug report.  Yeah, general file-like objects aren't supported at the moment, but I'm not opposed to this.  I didn't bother because I didn't know there were any use cases.

Something like your proposed solution is what we would need to do, but I would prefer to avoid that usage of `isinstance` because it's too specific.  Maybe directly checking for the existence of the file descriptor is the right way.

I'll probably get around to this next week, unless you want to make a pull request.
