### ISSUE TITLE
meshio with PLY support

### ISSUE THREAD

**Issue by nschloe** [dranjan/python-plyfile#29]
Hi everyone,

I've just updated [meshio](https://github.com/nschloe/meshio) to support PLY as well, and while its capabilities are certainly not on par with plyfile yet (it does support ascii and binary, point data, but no cell data yet), perhaps it's worth noting.

Cheers,
Nico

**Comment by dranjan** [comment]
Thanks for the note.  I don't think I've come across `meshio` before.  It looks like our two projects have slightly different aims, since `plyfile` is meant to be a generic interface to the PLY format that is completely indifferent to the elements contained therein, be they vertices, faces, or anything else.

I don't think `plyfile` needs to do anything about this, so I will close the issue.
