### ISSUE TITLE
Possibly switch licence to LGPL

### ISSUE THREAD

**Issue by mabl** [dranjan/python-plyfile#3]
Hi @dranjan,

thank you for this great work. Without wanting to start a flamewar, I wonder if you though about the licence.

IMHO a library is often best suited to be LGPL where one has to contribute back on the library code but is free to embed it into their own application.

Do you have any thought on the matter?

**Comment by dranjan** [comment]
@rogerwarburton Please create a separate issue.

**Comment by rogerwarburton** [comment]
OK, sorry.

**Comment by dranjan** [comment]
I see your point, and in my opinion both LGPL and GPL are good licenses. In practical terms, re-licensing under more permissive terms is quite difficult because the project has accepted contributions from several individuals, so they would all need to agree to have their work re-licensed as well. If hypothetically that were to occur, I would be open to changing the license, but I don't have the desire to go track all past contributors down, so for now I think we're keeping the regular GPL.

(To be clear, the problem also existed when this issue was created, but obviously to a lesser extent.)
