### ISSUE TITLE
plyfile.PlyElementParseError: element 'vertex': row 0: property 'green': early end-of-line

### ISSUE THREAD

**Issue by benthebear93** [dranjan/python-plyfile#44]
I have been trying to use PlyData.read for my code.
and it gives this error 

Traceback (most recent call last):
  File "simple_viewer.py", line 6, in <module>
    data = PlyData.read(filepath + '/ply_view.ply')['vertex']
  File "/home/benlee/.local/lib/python2.7/site-packages/plyfile.py", line 397, in read
    elt._read(stream, data.text, data.byte_order, mmap)
  File "/home/benlee/.local/lib/python2.7/site-packages/plyfile.py", line 642, in _read
    self._read_txt(stream)
  File "/home/benlee/.local/lib/python2.7/site-packages/plyfile.py", line 697, in _read_txt
    self, k, prop)
plyfile.PlyElementParseError: element 'vertex': row 0: property 'green': early end-of-line

ply data was made from pcd file which aquired by intel realsense d435i in gazebo simulation
pcd to ply command was made by "pcl_pcd2ply -format 0 pcd_file.pcd ply_file.ply"

maybe some error during converting pcd to ply?
or maybe some error in pcd data(or ply data)?

**Comment by dranjan** [comment]
*Usually* this means the PLY file itself is invalid, but it could also by a `plyfile` bug. It's impossible to say without seeing the PLY file, though. Since apparently the problems start immediately, it should be sufficient to share just the header and a few lines after it.

**Comment by benthebear93** [comment]
@dranjan  sorry, i didn't know how to see the header when i issue this but now i got the header!

ply
format ascii 1.0
comment PCL generated
element vertex 307200
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
element camera 1
property float view_px
property float view_py
property float view_pz
property float x_axisx
property float x_axisy
property float x_axisz
property float y_axisx
property float y_axisy
property float y_axisz
property float z_axisx
property float z_axisy
property float z_axisz
property float focal
property float scalex
property float scaley
property float centerx
property float centery
property int viewportx
property int viewporty
property float k1
property float k2
end_header
-0.39193749 -0.29379976 0.67991608 10197915
-0.39071074 -0.29379976 0.67991602 10197915
-0.38948402 -0.29379976 0.67991602 10197915

and this ply file was converted from below pcd file.
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z rgb
SIZE 4 4 4 4
TYPE F F F U
COUNT 1 1 1 1
WIDTH 640
HEIGHT 480
VIEWPOINT 0 0 0 1 0 0 0
POINTS 307200
DATA ascii
-0.39195254 -0.29381105 0.67994219 3684408
-0.39072567 -0.29381096 0.67994201 3684408
-0.38949883 -0.29381093 0.67994189 3684408

any problem in .ply file?

**Comment by dranjan** [comment]
Yeah, it appears your PLY file is invalid. The header specifies six properties for each vertex: `x`, `y`, `z`, `red`, `green`, `blue`, but each vertex line (the ones immediately following the header) only has four properties. If I had to guess, it looks like the three supposed unsigned character fields `red`, `green`, and `blue` were accidentally encoded together as a single unsigned integer (10197915 being the decimal representation of 0x9b9b9b).

This could be a bug in the tool you used to generate the PLY file.

If you want a quick fix, you could replace these lines in the header:
```
property uchar red
property uchar green
property uchar blue
```
with the single line
```
property uint rgb
```

which should allow `plyfile` to at least open the file, but I think most other tools would still choke on it. You would also need additional logic to interpret the color information property.

Since this isn't a `plyfile` bug, I'm going to close this issue. Good luck!

**Comment by benthebear93** [comment]
Great! thx for the advice !
