### ISSUE TITLE
How to get X,Y,Z value from ply file of a specific vertex or coordinates.

### ISSUE THREAD

**Issue by Aqil1214** [dranjan/python-plyfile#45]
I have a ply file generated from the Zed stereo camera. I also have a 2d image that corresponds to the ply file. 
Using OpenCV I have measured X and Y values but I am missing the Z value.

Is there any way, that I input the X and Y value plyfile module and it will get me the Z value of those values from the ply file. ?

Any help would be highly appriciated. Thank you

**Comment by dranjan** [comment]
If I understand the question: `plyfile` doesn't provide a method for this, but I guess you could iterate through the points until you find the XY values you want?  If that's too slow and you have many values to look up, you should probably preprocess the points into a more efficient data structure, like an XY-indexed table perhaps, or a quadtree (or similar) if you need something more sophisticated.

`plyfile` will read the file for you and give you a `numpy` array with the vertices, but that's pretty much all I can say given the information you provided.  Therefore, I'm closing this issue because it seems to lie beyond the scope of this package.  If you disagree, please provide more information.
